# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Assignment1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.3'
  pod 'Kingfisher', '~> 3.3'
  pod 'MBProgressHUD', '~> 1.0.0'
  
  # Pods for Assignment1

  target 'Assignment1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Assignment1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
